# This will run on Travis' 'new' container-based infrastructure
os:
  - linux

branches:
  only:
    - master
    - dev

dist: focal
addons:
  apt:
    # sources:
    #   - sourceline: 'ppa:chris-lea/redis-server'
    packages:
      - g++
      - libcurl4-openssl-dev
      - libpng-dev libqt5sql5-mysql
      - libqt5websockets5
      - libqt5websockets5-dev
      - libwebsockets-dev
      - make
      - qt5-default
      - qtchooser
      - zlib1g
      - zlib1g-dev
      - zlibc
      - python3-pip
      - python3-setuptools

services:
  - mysql

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++ libcurl4-openssl-dev libpng-dev libqt5sql5-mysql libqt5websockets5 libqt5websockets5-dev libwebsockets-dev make qt5-default qtchooser zlib1g zlib1g-dev zlibc
  - sudo apt-get install -y python3-pip python3-setuptools
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `fhqtravis` CHARACTER SET utf8 COLLATE utf8_general_ci;'

jobs:
  include:
    - language: cpp
      script:
        - ./ci/travis/run1_language_cpp.sh
    - language: node_js
      node_js:
        - 14
      script:
        - ./ci/travis/run2_language_node_js.sh
    - language: python
      python:
        - "3.7"
      install:
        - pip3 install websocket-client
        - pip3 install requests
        - pip3 install pylint
        - pip3 install pytest
        - pip3 install docker
        - pip3 install pytest-env
      script:
        - ./ci/travis/run3_language_python.sh

notifications:
  email:
    - freehackquest@gmail.com
